In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

# Creating Arrays

In [3]:
"""Creating Arrays
1. Create a 1D array with 20 random integers between 1 and 100.
Hint: Use the np.random.randint() function, specifying the range and size.

2. Create a 5x5 matrix where all the border elements are 1, and the inside elements are 0.
3. Create a diagonal matrix with values [1, 2, 3, 4] on the diagonal.
4. Create an array of shape (3, 3) where each row contains numbers from 1 to 3.
Hint: Use np.tile() to repeat arrays along rows or columns.

5. Create a 1D array with alternating 0s and 1s of length 10.
6. Create a 3x3 matrix with random integers between 10 and 20, and set the datatype to int32."""

'Creating Arrays\n1. Create a 1D array with 20 random integers between 1 and 100.\nHint: Use the np.random.randint() function, specifying the range and size.\n\n2. Create a 5x5 matrix where all the border elements are 1, and the inside elements are 0.\n3. Create a diagonal matrix with values [1, 2, 3, 4] on the diagonal.\n4. Create an array of shape (3, 3) where each row contains numbers from 1 to 3.\nHint: Use np.tile() to repeat arrays along rows or columns.\n\n5. Create a 1D array with alternating 0s and 1s of length 10.\n6. Create a 3x3 matrix with random integers between 10 and 20, and set the datatype to int32.'

In [4]:
# Ques 1 ->
random_arr = np.random.randint(0, 101, 20)
print(random_arr)

[76 74 26 99 30 96 79 58 28 56 37 39 61 93 11 34 86 76 46 73]


In [5]:
# Ques 2 ->
border_arr = np.ones((5, 5))
border_arr[1:-1, 1:-1] = 0 # making the inner element zero(0) 
print(border_arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
# Ques 3 ->
diag_elem = [1, 2, 3, 4]
diagonal_arr = np.array(diag_elem)
diagonal_martix = np.diag(diagonal_arr)
print(diagonal_martix)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [7]:
# Ques 4 ->
values = np.array([1, 2, 3])
array = np.tile(values, (3, 1)) # if ndim < then it makes (_first,_) _first automatically repeat 
print(array)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [8]:
# Ques 5 
array = np.tile([0, 1], 5) # repeating the array [0,1], 5 times
print(array)

[0 1 0 1 0 1 0 1 0 1]


In [9]:
# Ques 6
raandom_arr = np.random.randint(10, 21, (3, 3), dtype = np.int32) # (low, high, size, data_type)
print(random_arr)

[76 74 26 99 30 96 79 58 28 56 37 39 61 93 11 34 86 76 46 73]


# Array Attributes

In [10]:
"""Array Attributes
1. Create a NumPy array of shape (4, 5) filled with random integers between 1 and 10. Now use an appropriate attribute of an array and find the following:
shape of the array
size of the array
number of dimensions
data type
2. Write a Python function that takes an array as input and returns the number of dimensions (ndim) of the array.
Test the function with the following arrays:

A 1D array with 5 elements.
A 2D array of size (3x4).
A 3D array of size (2x3x4).
3. Create a NumPy array with the elements between 1 to 100 and use the dtype attribute to find out the data type of the elements. Modify the program to create arrays with elements of type float and string, and observe the changes in dtype.
4. Write a Python function that:
Creates a 6×3 array of integers using NumPy.
Prints the shape of the array using the shape attribute.
Reshapes the array to 3×6 and prints the new shape.
5. Write a program to:
Create an array of any size with all elements being 0 and use the appropriate attribute to print the size (in bytes) of each element in the array.
Create an array of any size with elements between 1 to 10 and print the size.
Create another array with floating-point numbers of any size and observe how the size changes."""

'Array Attributes\n1. Create a NumPy array of shape (4, 5) filled with random integers between 1 and 10. Now use an appropriate attribute of an array and find the following:\nshape of the array\nsize of the array\nnumber of dimensions\ndata type\n2. Write a Python function that takes an array as input and returns the number of dimensions (ndim) of the array.\nTest the function with the following arrays:\n\nA 1D array with 5 elements.\nA 2D array of size (3x4).\nA 3D array of size (2x3x4).\n3. Create a NumPy array with the elements between 1 to 100 and use the dtype attribute to find out the data type of the elements. Modify the program to create arrays with elements of type float and string, and observe the changes in dtype.\n4. Write a Python function that:\nCreates a 6×3 array of integers using NumPy.\nPrints the shape of the array using the shape attribute.\nReshapes the array to 3×6 and prints the new shape.\n5. Write a program to:\nCreate an array of any size with all elements bei

In [11]:
# Ques 1
random_arr = np.random.randint(low=1, high=11, size=(4, 5))
print("Shape of the array :", random_arr.shape)
print("Size of the array :", random_arr.size)
print("Dimensions of the array :", random_arr.ndim)
print("Data Type of the array :", random_arr.dtype)


Shape of the array : (4, 5)
Size of the array : 20
Dimensions of the array : 2
Data Type of the array : int32


In [12]:
# Ques 2
def get_array_dimensions(array):
    return array.ndim # return dimensions 
    
# 1D array with 5 elements
array_1d = np.random.rand(5)
print(f"1D Array dimensions: {get_array_dimensions(array_1d)}")  # Expected: 1

# 2D array of size (3x4)
array_2d = np.random.rand(3, 4)
print(f"2D Array dimensions: {get_array_dimensions(array_2d)}")  # Expected: 2

# 3D array of size (2x3x4)
array_3d = np.random.rand(2, 3, 4)
print(f"3D Array dimensions: {get_array_dimensions(array_3d)}")  # Expected: 3

1D Array dimensions: 1
2D Array dimensions: 2
3D Array dimensions: 3


In [30]:
# Ques 3 

# a random array with elements between 1 and 100
array_random_int = np.random.randint(1, 101, size=20)
print(f"Data Type of Random Integer Array: {array_random_int.dtype} \n")  # Expected: int32 or int64

# type to float
array_random_float = array_random_int.astype(float)
print(f"Data Type of Random Float Array: {array_random_float.dtype} \n")  # Expected: float64

# type to string
array_random_string = array_random_int.astype(str)
print(f"Data Type of Random String Array: {array_random_string.dtype} \n")  # Expected: <U*


Data Type of Random Integer Array: int32 

Data Type of Random Float Array: float64 

Data Type of Random String Array: <U11 



In [34]:
# Ques 3 (OR)

# Array with integers from 1 to 100
array_int = np.arange(1, 101)
print(f"Data Type of Integer Array: {array_int.dtype}")

# Array with elements converted to float
array_float = array_int.astype(float)
print(f"Data Type of Float Array: {array_float.dtype}")

# Array with elements converted to string
array_string = array_int.astype(str)
print(f"Data Type of String Array: {array_string.dtype}") 

Data Type of Integer Array: int64
Data Type of Float Array: float64
Data Type of String Array: <U21


In [40]:
# Ques 4
def array_operations():
    arr = np.random.randint(1, 100, size=(6, 3)) # Create a 6x3 array of integers
    # print(arr)
    print("Original shape:", arr.shape) # Print the shape of the original array
    
    reshaped_arr = arr.reshape(3, 6) #  Reshape the array to 3x6 and print the new shape
    # print(reshaped_arr)
    print("Reshaped shape:", reshaped_arr.shape)
    
array_operations() # function 

Original shape: (6, 3)
Reshaped shape: (3, 6)


In [13]:
# Ques 5

zero_array = np.zeros((4, 4), dtype=int)
print("Size of each element (in bytes):", zero_array.itemsize)

random_array = np.random.randint(1, 11, size=(3, 3))
print("Size of each element (in bytes):", random_array.itemsize)

float_array = [1.0, 2.0, 3.0]
float_array = np.array(float_array)
print("Size of each element (in bytes):", float_array.itemsize)


Size of each element (in bytes): 8
Size of each element (in bytes): 4
Size of each element (in bytes): 8


# Sorting and Partioning

In [ ]:
"""Sorting and Partioning
1. Given an array arr, sort the array in ascending order without modifying the original array. Print both the original and sorted arrays.(use np.sort())
2. You have arr = np.array([50, 30, 40, 20]) and names = np.array(["A", "B", "C", "D"]).
Sort the arr values in ascending order and rearrange the names array accordingly.(use np.argsort() to get sorted indices and reorder names)

3. Write code to find the k smallest elements from the array arr. Print these elements in ascending order.(use np.partition())
4. Partition the array arr such that all elements smaller than a particular number(user input) appear before those greater than or equal to that number. Print the partitioned array.(use np.partition() to find the pivot value's index)
5. Sort each row of a 2D array arr in ascending order.(use np.sort() with axis parameter)
6. Print k largest elements of an array arr in descending order.(use np.partition() to find top k elements)
7. Given an array arr(containing possible negative values), sort the array in ascending order based on the absolute values of the elements. Print the sorted array.(use np.argsort() with a custom key for absolute values)
8. Given an array arr, sort only the elements greater than k in ascending order, keeping the other elements in their original positions.(create a mask to find elements greater than k, use np.sort() to sort them then reassign the sorted values back to their original indices in the array)"""

In [31]:
# Ques 1
arr =np.array([2,3,4,9,6,67,42])
sorted_arr=np.sort(arr)
print(arr)
print(sorted_arr)

[ 2  3  4  9  6 67 42]
[ 2  3  4  6  9 42 67]


In [32]:
# Ques 2
arr = np.array([50, 30, 40, 20])
names = np.array(["A", "B", "C", "D"])
sorted_indices = np.argsort(arr)
sorted_arr = arr[sorted_indices]
sorted_names = names[sorted_indices]

print("sorted arr:", sorted_arr)
print("sorted names:", sorted_names)

sorted arr: [20 30 40 50]
sorted names: ['D' 'B' 'C' 'A']


In [33]:
# Ques 3
arr = np.array([60, 30, 10, 20, 40, 50, 70])
k = 3
k_smallest = np.partition(arr, k)[:k]
sorted_k_arr = np.sort(k_smallest)
print(sorted_k_arr)

[10 20 30]


In [34]:
# Ques 4
arr = np.array([60, 30, 40, 20, 10, 70, 50])
pivot_value = int(input())
partitioned_arr = np.partition(arr, k)
final_arr=np.sort(partitioned_arr)
print("partitioned array", partitioned_arr)

 40


partitioned array [10 20 30 40 50 60 70]


In [35]:
# Ques 5
arr = np.array([[60, 30, 40], 
                [20, 10, 70], 
                [80, 50, 90]])
sorted_arr = np.sort(arr, axis=1)
print(sorted_arr)

[[30 40 60]
 [10 20 70]
 [50 80 90]]


In [39]:
# Ques 6
arr = np.array([60, 30, 40, 20, 10, 70, 50])
k = int(input("enter the value of K:"))
partitioned_arr = np.partition(arr, -k)
print(partitioned_arr)
top_k_elements = np.sort(partitioned_arr[-k:])[::-1]
print(top_k_elements)

enter the value of K: 5


[10 20 30 40 50 60 70]
[70 60 50 40 30]


# Indexing and Slicing


In [ ]:
"""Indexing and slicing
1. 2D Array Indexing
Consider the following 2D array: arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

Access the element at row index 1 and column index 2.
Extract the first row.
Extract the last column.
2. Boolean Indexing
Given an array arr = np.array([2, 5, 8, 11, 14, 17, 20]), use boolean indexing to:

Extract all values greater than 10.
Replace all values greater than 15 with -1.
3. Fancy Indexing
Using the 2D array arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]]), write code to:

Select the elements at positions (0,2), (1,1), and (2,0).

Use fancy indexing to create a submatrix with rows 0 and 2, and columns 1 and 2.

Hint:

For 1st part, use arrays of row and column indices
For 2nd part, you can create a submatrix using fancy indexing by using np.newaxis to match the dimensions
4. Slicing 1D array
Given the array arr = np.array([1, 3, 5, 7, 9, 11, 13, 15]), write code to:

Extract the first 4 elements.
Extract every second element from the entire array.
Extract elements from index 2 to the end, stepping by 2.
5. Slicing a 2D Array
Given the following 2D array: arr_2d = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]])

Slice and print the last two columns of 1st row.
Slice and print the last row, reversed.
6. Handling Out-of-Range Indices in Slicing vs. Indexing
Given the array: arr = np.array([10, 20, 30, 40, 50])

What will be the output of the following slicing operations? Explain why they work, even though some indices are out of range.

print(arr[2:10])
print(arr[-10:3])
Compare the behavior of slicing to accessing a single element with an out-of-range index (e.g., arr[10]). Why does slicing not raise an error in these cases, but indexing does?

7. Work with an Audio File
Download the audio file from the following link: Simple Logo - Pixabay. Load the audio file using pydub and complete the following tasks:

Extract the first second of the audio and plot its waveform.

Hint: Use the frame rate to calculate how many samples are in 1 second, and use slicing to extract this part.
Extract the last second of the audio and plot its waveform.

Combine the samples from the first second and the last second into a new array and plot the combined waveform.
Hint: Use NumPy’s np.concatenate() function to merge the two slices."""

In [22]:
# Ques 1
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

element = arr_2d[1, 2]
print(f"Element at row index 1 and column index 2: {element}")

first_row = arr_2d[0, :]
print(f"First row: {first_row}")

last_column = arr_2d[:, -1]
print(f"Last column: {last_column}")

Element at row index 1 and column index 2: 30
First row: [ 5 10 15]
Last column: [15 30 45]


In [23]:
# Ques 2
arr = np.array([2, 5, 8, 11, 14, 17, 20])
mask=arr>10
values_greater_than_10 = arr[mask]
arr[arr > 15] = -1
print(values_greater_than_10)
print(arr)

[11 14 17 20]
[ 2  5  8 11 14 -1 -1]


In [24]:
# Ques 3
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

# elements at positions (0,2), (1,1), and (2,0)
row_indices = [0, 1, 2]
col_indices = [2, 1, 0]
selected_elements = arr_2d[row_indices, col_indices]
print("Selected elements:",selected_elements)

rows = np.array([0, 2])[:, np.newaxis]  # changing [0,2] to [[0],[2]]
cols = np.array([1, 2])  
submatrix = arr_2d[rows, cols] # cartition product 
print("Submatrix using np.newaxis:", submatrix)

Selected elements: [15 25 35]
Submatrix using np.newaxis: [[10 15]
 [40 45]]


In [26]:
# Ques 4
arr = np.array([1, 3, 5, 7, 9, 11, 13, 15])
first_4_elements = arr[:4]
every_second_element = arr[::2]
elements_from_2_to_end_step_2 = arr[2::2]
print("First 4 elements:", first_4_elements)
print("Every second element:", every_second_element)
print("Elements from index 2 to the end, stepping by 2:", elements_from_2_to_end_step_2)

First 4 elements: [1 3 5 7]
Every second element: [ 1  5  9 13]
Elements from index 2 to the end, stepping by 2: [ 5  9 13]


In [71]:
# Ques 5
arr_2d = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]])

last_two_column = arr_2d[0, -2:]
print("The last two columns of first row:",last_two_column)

last_row_reversed = arr_2d[-1, ::-1]
print("Last row reversed:", last_row_reversed)


The last two columns of first row: [30 40]
Last row reversed: [120 110 100  90]


In [30]:
# Ques 6
arr = np.array([10, 20, 30, 40, 50])
print("array range from 2 to 10:",arr[2:10])
print("array range from -10 to 3:",arr[-10:3])
#In NumPy, slicing allows us to extract a part of an array by specifying a range of indices. When the indices are out of range, NumPy handles it differently compared to accessing an element using an index. For example, in the operation `arr[2:10]` with `arr = np.array([10, 20, 30, 40, 50])`, the start index is `2`, which refers to the element `30`, and the end index is `10`. Since the array has only 5 elements, the end index `10` is out of range. However, NumPy does not raise an error in this case. Instead, it simply returns all elements from index `2` to the end of the array, resulting in `[30, 40, 50]`.
#Similarly, in the slicing operation `arr[-10:3]`, the start index `-10` is out of range and refers to a position before the array begins. Negative indices count from the end of the array, and in this case, `-10` is beyond the start of the array. NumPy treats this as `0`, meaning it starts at the first element of the array. The end index `3` refers to the element at index `3`, which is `40`. Therefore, the result of `arr[-10:3]` is `[10, 20, 30]`.
#The reason NumPy behaves this way is that slicing is designed to be to be used for extracting subarrays or views of the original array without requiring strict bounds checking. If the end index exceeds the size of the array, NumPy simply returns all elements up to the end, ensuring that you don’t lose data. Similarly, when negative indices are used and exceed the beginning of the array, NumPy treats them as `0` to avoid errors. This flexibility allows for cleaner and more efficient code, especially when working with dynamic or unknown array sizes.
#In contrast, indexing (e.g., `arr[10]`) is used to access a single element at a specific index. In this case, the index must be valid, and if it is out of range, NumPy raises an `IndexError` because there is no element at that index. Indexing expects an exact location, so an out-of-bounds index is considered an error.

array range from 2 to 10: [30 40 50]
array range from -10 to 3: [10 20 30]


In [3]:
#ques7
arr = np.array([-7, 4, -3, 2, -5, 6, -1])

sorted_indices = np.argsort(np.abs(arr))
sorted_array = arr[sorted_indices]

print(sorted_array)


[-1  2 -3  4 -5  6 -7]


In [4]:
#ques8
arr = np.array([10, 3, 7, 2, 8, 6, 1, 9])
k = 5

mask = arr > k
greater_than_k = arr[mask]
sorted_greater = np.sort(greater_than_k)
arr[mask] = sorted_greater

print(arr)


[ 6  3  7  2  8  9  1 10]


# Reshaping in NumPy


In [ ]:
"""Reshaping in NumPy
1. Create a 2D array of shape (3, 5). Flatten it into a 1D array and then reshape it back into a (5, 3) array.
2. Create a 1D array
arr = np.array([1, 2, 3, 4, 5])
Reshape arr into (5,1), then convert to (5,) and then convert it into (1,5).
3. Create a 1D NumPy array with values ranging from 1 to 100. Reshape it into a (10, 10) matrix. Apply '.ravel()' and '.flatten()' on the matrix and modify the original matrix. Compare the outputs of both methods and explain the difference in memory sharing.
4. Generate a 5x5 NumPy matrix representing pixel intensities from an image. Use slicing to extract the central 3x3 section of the matrix and flatten it. How does reshaping impact the spatial relationships of the pixels?
5. Create a 3-channel RGB image as a NumPy array of shape (3, 4, 4) with random integer values between 0 and 255. Flatten the image using '.reshape()' and reshape it back to its original shape. Explain the order of pixel data stored and how reshaping affects the channel structure."""

In [40]:
# Ques 1
array_2d = np.arange(1, 16).reshape(3, 5)
array_1d = array_2d.flatten()
reshaped_array = array_1d.reshape(5, 3)
print("Original 2D array:\n", array_2d)
print("Flattened 1D array:\n", array_1d)
print("Reshaped array (5, 3):\n", reshaped_array)

Original 2D array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Flattened 1D array:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Reshaped array (5, 3):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [42]:
# Ques 2
arr = np.array([1, 2, 3, 4, 5])
reshaped_5_1 = arr.reshape(5, 1)
reshaped_5 = reshaped_5_1.reshape(5,)
reshaped_1_5 = reshaped_5.reshape(1, 5)

print("Reshaped into (5, 1):\n", reshaped_5_1)
print("Converted back to (5,):\n", reshaped_5)
print("Reshaped into (1, 5):\n", reshaped_1_5)


Reshaped into (5, 1):
 [[1]
 [2]
 [3]
 [4]
 [5]]
Converted back to (5,):
 [1 2 3 4 5]
Reshaped into (1, 5):
 [[1 2 3 4 5]]


In [43]:
# Ques 3
array_1d = np.arange(1, 101)
matrix_10x10 = array_1d.reshape(10, 10)
ravel_output = matrix_10x10.ravel()
flatten_output = matrix_10x10.flatten()
matrix_10x10[0, 1] = 999

print("Output of .ravel():", ravel_output)
print("Output of .flatten():", flatten_output)
print("Modified Matrix:\n", matrix_10x10)
#The .ravel() method flattens the matrix into a 1D array, but it shares the memory with the original array. Any changes to the original matrix will reflect in this array.
#The .flatten() method also flattens the matrix into a 1D array, but it creates a new copy. Changes to the original matrix will not affect this array.

Output of .ravel(): [  1 999   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
Output of .flatten(): [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
Modified Matrix:
 [[  1 999   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  3

# Universal Functions

In [ ]:
"""Universal Functions
Q1) Given an array x = [1, 4, 9, 16, 25], compute the square root of each element in the array and print the result.

Q2) Create an array angles =[0,  π2 ,  π ,  3π2 ] , calculate the sine of each angle and print the result.

Q3) Given two arrays a =[True, False, True] and b = [False, False, True], perform an element-wise logical AND operation and print the result.

Q4) Create two arrays x = [1, 2, 3, 4] and y = [2, 2, 3, 5], perform an element-wise comparison (x < y) and print the result.

Q5) Create an array x =[-2, -1, 0, 1, 2, 3, 4], compute the following element-wise operation:

If an element is negative, square it.
If an element is non-negative, compute its exponential. Print the resulting array."""

In [73]:
# Ques 1
arr_x = np.array([1, 4, 9, 16, 25])
sqroot_arr = arr_x ** (1/2)
print(sqroot_arr)

[1. 2. 3. 4. 5.]


In [82]:
# Ques 2
angles = np.array([0, np.pi/2, np.pi, 3*np.pi/2])
sine_result = np.sin(angles)
print("Sine of each angle:", np.round(sine_result, 2))

Sine of each angle: [ 0.  1.  0. -1.]


In [84]:
# Ques 3
boolean_arr1 = [True, False, True]
boolean_arr2 = [False, False, True]
and_result = np.logical_and(boolean_arr1,boolean_arr2)
print("element-wise logical AND operation:",and_result)

element-wise logical AND operation: [False False  True]


In [44]:
# Ques 4
x = np.array([1, 2, 3, 4])
y = np.array([2, 2, 3, 5])
result = x < y
print(result)

[ True False False  True]


In [90]:
# Ques 5
x = np.array([-2, -1, 0, 1, 2, 3, 4])

operation_result = np.where(x < 0, x**2, np.exp(x))

print("Element-wise operation result:",np.round(operation_result, 2))

Element-wise operation result: [ 4.    1.    1.    2.72  7.39 20.09 54.6 ]


# Aggregations


In [46]:
#question 1----------> 

arr = np.random.randint(1, 100, 10)
print("Array:", arr)

sum_arr = np.sum(arr)
print(f"sum : {sum_arr}")

mean_arr = np.mean(arr)
print(f"mean : {mean_arr}")

std_dev_arr = np.std(arr)
print(f"standard deviation : {std_dev_arr}")

result = 5 * np.min(arr) - 3 * np.max(arr)
print(f"result : {result}")

Array: [11 32 62 95 62 70 69 56 47  3]
sum : 507
mean : 50.7
standard deviation : 26.773307602909284
result : -270


In [47]:
#question2 ----------------->

matrix = np.random.randint(1, 51, size=(4, 5))
print(matrix)
mean = np.mean(matrix)
print(mean)
sumrow = np.sum(matrix, axis=1)
print(sumrow)

[[48  5 17 30 34]
 [18 10 45 34  9]
 [ 2 21 17 35 22]
 [20 23 35 29  5]]
22.95
[134 116  97 112]


In [48]:
#question3---------------------->

matrix = np.random.randint(1, 11, size=(3, 3))
print(matrix)
mincol = np.min(matrix, axis=0)
print(mincol)
maxrow = np.max(matrix, axis=1)
print( maxrow)
result = np.min(maxrow) - np.max(mincol)
print("Minimum of list max - Maximum of list min:", result)

[[5 8 7]
 [5 2 7]
 [2 7 2]]
[2 2 2]
[8 7 7]
Minimum of list max - Maximum of list min: 5


In [49]:
#question4 ------------------------>

data = np.array([15, 25, 35, 45, 55, 65])
minval = np.min(data)
print( minval)
modified_data = data - minval
print(modified_data)
meanmod = np.mean(modified_data)
print(meanmod)

15
[ 0 10 20 30 40 50]
25.0


In [50]:
#question5------------------>

arr = np.array([3, 5, 7, 9, 11])
cumulativesum = np.cumsum(arr) 
print(cumulativesum)
cumulativeprod = np.cumprod(arr)
print(cumulativeprod)

[ 3  8 15 24 35]
[    3    15   105   945 10395]


In [51]:
#question6--------------------->

scores = np.array([[85, 92, 78], [88, 76, 95], [91, 89, 82], [75, 85, 88]])
avg_score_stu = np.mean(scores, axis=1)
print(avg_score_stu)
high_score_per_sub = np.max(scores, axis=0)
print(high_score_per_sub)
tot_avg_score = np.mean(scores)
print(tot_avg_score)

[85.         86.33333333 87.33333333 82.66666667]
[91 92 95]
85.33333333333333


# Broadcasting

In [52]:
#ques1
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([10, 20, 30])
result = A + B
print("Resulting Array:\n", result)
print("Shape of the Resulting Array:", result.shape)


Resulting Array:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]
Shape of the Resulting Array: (3, 3)


In [53]:
#ques2
def check_broadcasting(shape1, shape2):
    try:
        np.broadcast(np.empty(shape1), np.empty(shape2))
        result_shape = np.broadcast(np.empty(shape1), np.empty(shape2)).shape
        return (True, result_shape)
    except ValueError:
        return (False, None)
test_cases = [
    ((3, 4), (4,)),
    ((2, 1, 5), (3, 5)),
    ((2, 3), (2,))
]

for shape1, shape2 in test_cases:
    can_broadcast, result_shape = check_broadcasting(shape1, shape2)
    if can_broadcast:
        print(f"Shapes {shape1} and {shape2} are broadcast-compatible. Resulting shape: {result_shape}")
    else:
        print(f"Shapes {shape1} and {shape2} cannot be broadcast.")


Shapes (3, 4) and (4,) are broadcast-compatible. Resulting shape: (3, 4)
Shapes (2, 1, 5) and (3, 5) are broadcast-compatible. Resulting shape: (2, 3, 5)
Shapes (2, 3) and (2,) cannot be broadcast.


In [54]:
#ques3
A = np.random.randint(1, 11, size=(3, 5))
B = np.random.randint(1, 6, size=(5,))
result = A - B
print("Array A:\n", A)
print("Array B:\n", B)
print("Result of A - B:\n", result)


Array A:
 [[ 8  9  3  9  8]
 [ 1  7 10  8  9]
 [ 1  9 10  5  2]]
Array B:
 [4 4 5 3 1]
Result of A - B:
 [[ 4  5 -2  6  7]
 [-3  3  5  5  8]
 [-3  5  5  2  1]]


In [55]:
#ques4
A = np.random.randint(0, 11, size=(2, 4, 3))
B = np.full((4, 3), 5)
result = A + B
print("Array A (3D):\n", A)
print("Array B (2D):\n", B)
print("Result of A + B:\n", result)


Array A (3D):
 [[[ 9  6  9]
  [ 9  9 10]
  [ 0  1  7]
  [ 2  0  2]]

 [[ 8  2  8]
  [ 7  0  2]
  [10 10  9]
  [ 8  1  3]]]
Array B (2D):
 [[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]
Result of A + B:
 [[[14 11 14]
  [14 14 15]
  [ 5  6 12]
  [ 7  5  7]]

 [[13  7 13]
  [12  5  7]
  [15 15 14]
  [13  6  8]]]


In [56]:
#ques5
image = np.random.randint(0, 256, size=(32, 32))
scaled_image = image * 0.5
print("Original Image:\n", image)
print("Scaled Image:\n", scaled_image)


Original Image:
 [[ 35  58  98 ...  54 199 174]
 [139 112   0 ... 203  37  72]
 [ 45 217  74 ...  38 166 204]
 ...
 [151  57 180 ...   9  97 147]
 [ 70  87 114 ... 246 124  42]
 [228 190 186 ...  62 182  59]]
Scaled Image:
 [[ 17.5  29.   49.  ...  27.   99.5  87. ]
 [ 69.5  56.    0.  ... 101.5  18.5  36. ]
 [ 22.5 108.5  37.  ...  19.   83.  102. ]
 ...
 [ 75.5  28.5  90.  ...   4.5  48.5  73.5]
 [ 35.   43.5  57.  ... 123.   62.   21. ]
 [114.   95.   93.  ...  31.   91.   29.5]]


In [57]:
#ques6
codes = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0], [1.0, 1.0, 1.0], [2.0, 3.0, 4.0]])
observation = np.array([3.0, 3.0, 3.0])

distances_squared = np.sum((codes - observation) ** 2, axis=1)
closest_index = np.argmin(distances_squared)
closest_distance_squared = distances_squared[closest_index]
closest_distance = np.sqrt(closest_distance_squared)

print(f"Index of the closest code: {closest_index}")
print(f"Squared Euclidean distance to the closest code: {closest_distance_squared}")
print(f"Euclidean distance to the closest code: {closest_distance}")


Index of the closest code: 4
Squared Euclidean distance to the closest code: 2.0
Euclidean distance to the closest code: 1.4142135623730951


# Concatenation

In [58]:
#question1------------------->

arr1 = np.array([15, 45,34])
arr2 = np.array([23,34,24])
arr3 = np.array([76,32,12])
result = np.vstack((arr1, arr2, arr3))
print(result)

[[15 45 34]
 [23 34 24]
 [76 32 12]]


In [59]:
#question2 -------------->

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])
result = np.hstack((arr1, arr2, arr3))
print(result)

[1 2 3 4 5 6 7 8 9]


In [60]:
#question3----------------->

m = np.array([[2, 4], [3, 6]])
n = np.array([[4, 8], [5, 10]])
result = np.hstack((m, n))
print(result)

[[ 2  4  4  8]
 [ 3  6  5 10]]


In [61]:
#question4----------------->

a = np.array([11, 12, 13])
b = np.array([[14, 15, 16], [17, 18, 19]])
aree = a.reshape(1, -1)
result = np.vstack((aree, b))
print(result)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [62]:
#question5------------------->

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
z = np.array([[9, 10], [11, 12]])
concatcol = np.concatenate((x, y, z), axis=0)
print(concatcol)
concatrow = np.concatenate((x, y, z), axis=1)
print(concatrow)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]


# Boolean Masking

In [63]:
#question1 -------------->

arr = np.array([1, 3, 5, 7, 9, 2, 4, 8])
filter_arr = arr[arr <= 5]
print(filter_arr)

[1 3 5 2 4]


In [64]:
#question2--------------->

arr = np.array([[5, 12, 18], [7, 1, 3], [11, 6, 14]])
maskitem = arr[arr>10]
print(maskitem)

[12 18 11 14]


In [65]:
#question3------------>

arr = np.arange(11)
mask = arr%2!=0
odd_arr = arr[mask]
print(odd_arr)

[1 3 5 7 9]


In [66]:
#question4------------>

arr = np.array([1, 3, 6, 9, 12, 15])
mask_great5 = arr>5
mask_div3 = arr%3==0
comb_mask = mask_great5 & mask_div3
comb_arr = arr[comb_mask]
print(comb_arr)

[ 6  9 12 15]


In [67]:
#question5------------>

arr = np.array([[1, 7, 3], [9, 4, 5], [6, 2, 8]])
mask = arr < 5
arr[mask] = 0
print(arr)

[[0 7 0]
 [9 0 5]
 [6 0 8]]


In [68]:
#question6------------>

arr = np.array([1, 3, 6, 9, 12, 15, 4, 2, 8])
mask = arr > 5
modarr = arr[mask]
count = np.size(modarr)
# count = np.sum(mask)
print(count)

5
